### ISSUE TITLE
Invalid parameter not satisfying: (name != nil) && ([name length] > 0)

### ISSUE THREAD

**Issue by mogsten** [Yalantis/DisplaySwitcher#10]
Keep getting the error Invalid parameter not satisfying: (name != nil) && ([name length] > 0)
while loading the view, app works, everything works, just loading the view crashes the app.

**Comment by serejahh** [comment]
Hi @mogsten. Thanks for your interest! 

I didn't get what you mean. When do you get the error? When do you check the conditions?

**Comment by mogsten** [comment]
OK, I have fixed this, by setting xibName and id instead of passing variables, but now, nothing will show on the screen
I can see what happens when it switches from Grid to List but it disappears when the animation finishes

**Comment by serejahh** [comment]
Could you describe more details or provide your project?
