### ISSUE TITLE
Do not connect the dependence

### ISSUE THREAD

**Issue by Xotab4ik** [Yalantis/DisplaySwitcher#14]
[!] Unable to satisfy the following requirements:

- `DisplaySwitcher (~> 1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `DisplaySwitcher (~> 1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by serejahh** [comment]
Hi @Xotab4ik. I've pushed a new podspec. Now everything should work fine
