### ISSUE TITLE
Using in Objective-C project. 

### ISSUE THREAD

**Issue by lateAtNight** [Yalantis/DisplaySwitcher#15]
When using DisplaySwitcher in an Objective-C project the init method on DisplaySwitchLayout is `public init(staticCellHeight: CGFloat, nextLayoutStaticCellHeight: CGFloat, layoutState: LayoutState)` is not available to Obj-C code. The only init method is initWithCoder.

Using Xcode version 8.0 (8A218a) and macOS 10.12. iOS deployment target 10.0.

**Comment by serejahh** [comment]
Hi @lateAtNight! Thanks for your interest. I've just added compatibility. Please update to `1.0.1`
