### ISSUE TITLE
Changing TransitionLayout issue

### ISSUE THREAD

**Issue by DennisH511** [Yalantis/DisplaySwitcher#18]
## Report a bug
Hi,

Followed the useage guide in a simple project with a button to switch the layout. But trying to switch layout outputs the following error in the TransitionManager class:

> Could not cast value of type 'UICollectionViewTransitionLayout' (0x1775b1c) to 'DisplaySwitcher.TransitionLayout' (0xbff60).

![screen shot 2016-11-26 at 16 16 02](https://cloud.githubusercontent.com/assets/17709795/20641691/9efa8108-b3f5-11e6-9d44-2e5af2d81f89.png)

Have I missed something?

Thanks.

Btw - I tried setting the initial layout as the grid but the first view was still a list. Is that expected behaviour??

Xcode 8.1/swift 3

**Comment by serejahh** [comment]
Hi @DennisH511. Have you faced the same issue with the example app? There's also a "change layout" button

**Comment by ChanchalW** [comment]
Hi did you solved this, I am facing the same issue.
