### ISSUE TITLE
an error happened while carthage update 

### ISSUE THREAD

**Issue by hunter123321000** [Yalantis/DisplaySwitcher#21]
please help me 

while i carthage update , an error happened as below

Dependency "DisplaySwitcher" has no shared framework schemes
-------
while i pod install, another error happened

[!] Unable to find a specification for `DisplaySwitcher (~> 1.0)`

**Comment by douglas-srs** [comment]
I am facing the same issue

**Comment by Vodolazkyi** [comment]
Hi, try to specify `github "Yalantis/DisplaySwitcher" "master"`
Let me know if this helped

**Comment by douglas-srs** [comment]
It works now, thanks!

**Comment by Vodolazkyi** [comment]
Thank you for leaving this issue.
