### ISSUE TITLE
transition content offset issues

### ISSUE THREAD

**Issue by moliya** [Yalantis/DisplaySwitcher#29]
**report a bug**

when i set GridLayoutCountOfColumns = 2,the transition content offset is not correct
![untitled](https://user-images.githubusercontent.com/8399816/34924070-1ad1d3da-f9dc-11e7-8748-83b06494c19d.gif)

I am running Xcode 9.1
Simulator: Iphone X ios 11.1

**Comment by freaqed** [comment]
Hello, @moliya!
As you can see, `GridLayoutCountOfColumns` is static and private. It isn't developed to be dynamic, and DisplaySwitcher doesn't support it at all.
Feel free to tweak the code and open PR. Everyone who's facing the same problem would be glad to see it
