### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by LazyScream** [Yalantis/DisplaySwitcher#31]
i use the swift4 Branch 
at iPhoneX is awesome ! 
but in iPhone 6 、iPhoneSe like video 
https://goo.gl/TCwbw5
plz help me

**Comment by freaqed** [comment]
Hey, @LazyScream!
Please take a look at content inset of the collection since the logic of how it works changed in 11th SDK

**Comment by LazyScream** [comment]
what 's 11th SDK ?

**Comment by freaqed** [comment]
I mean iOS SDK 11

**Comment by LazyScream** [comment]
in iOS11 is ok 
iOS 10 is no ok ， so only support iOS11 ?

**Comment by freaqed** [comment]
Hello, @LazyScream 
Just checked example project on iOS 10.3 and iOS 11 devices. Everything works well.
Looks like your problem related to constrains. Try setting top constraint's second item to superview.
Closing as not related to the component
