### ISSUE TITLE
why require ios 8+

### ISSUE THREAD

**Issue by nvcken** [Yalantis/DisplaySwitcher#4]
Could it support ios 7 ?

**Comment by kvnbautista** [comment]
@nvcken Yes

**Comment by nvcken** [comment]
Could you explain more detail?
I saw this
```
Requirements

iOS 8.0+ (for component), iOS 9.0+ (for example)
Xcode 7
Swift 2
```

**Comment by kvnbautista** [comment]
In the project you can always change the deployment target to 7.0 from the project info. I switched to 7.0 and works just fine but this project does have iOS 8.0 components. i recommend 8.0 by the way.

**Comment by nvcken** [comment]
yes, thanks
