### ISSUE TITLE
customize cellPadding

### ISSUE THREAD

**Issue by leobouilloux** [Yalantis/DisplaySwitcher#9]
Hi,

Sorry for posting here, this is not really an issue.

I'd like to know if it's possible to set my own cell padding in the object BaseLayout.
I want a very thin space between cells in grid mode.

Kind regards,

**Comment by Roman-Scherbakov** [comment]
Hi, @leobouilloux 
Sorry, in this version you can't set custom padding, because cellPading property has _private_ access level. But you can extend functionality of component and make pull request. Thanks.

**Comment by leobouilloux** [comment]
Okay,

Thank you for your reply!
